
import React from 'react';
import { CLASSICAL_INTERSECTIONS, QUANTUM_INTERSECTIONS } from '../constants';

interface ConclusionProps {
  show: boolean;
  onReset: () => void;
}

const Conclusion: React.FC<ConclusionProps> = ({ show, onReset }) => {
  if (!show) return null;

  const reductionPercentage = Math.round(
    ((CLASSICAL_INTERSECTIONS - QUANTUM_INTERSECTIONS) / CLASSICAL_INTERSECTIONS) * 100
  );

  return (
    <div className="fixed inset-0 bg-black/80 backdrop-blur-xl flex items-center justify-center z-50 animate-fade-in">
      <div className="w-full max-w-4xl bg-gray-900/70 border border-cyan-500/50 rounded-2xl p-8 shadow-2xl shadow-cyan-500/20 m-4 flex flex-col md:flex-row gap-8">
        <div className="flex-1">
          <h2 className="text-3xl font-bold text-cyan-400 [text-shadow:0_0_10px_rgba(0,255,255,0.7)] mb-4">
            Simulation Complete: Theory Validated
          </h2>
          <p className="text-gray-300 mb-6">
            The Quantum-Accelerated Rendering Unit (QARU) successfully offloaded the ray-tracing search problem to the quantum co-processor.
          </p>
          <div className="space-y-4 text-lg">
            <div className="bg-gray-800/50 p-4 rounded-lg">
              <p className="text-gray-400">Computational Work Reduction</p>
              <p className="text-3xl font-bold text-green-400">{reductionPercentage}%</p>
            </div>
            <div className="bg-gray-800/50 p-4 rounded-lg">
              <p className="text-gray-400">Shader Energy Savings</p>
              <p className="text-3xl font-bold text-green-400">Proportional to work reduction</p>
            </div>
          </div>
          <button 
            onClick={onReset}
            className="mt-8 w-full px-6 py-3 text-lg font-bold rounded-lg transition-all duration-300 transform bg-cyan-500 text-gray-900 hover:bg-cyan-400 hover:scale-105 active:scale-100 shadow-[0_0_15px_rgba(0,255,255,0.5)] hover:shadow-[0_0_25px_rgba(0,255,255,0.8)]"
          >
            Run Simulation Again
          </button>
        </div>
        <div className="flex-1 flex flex-col items-center justify-center">
          <p className="font-semibold mb-2 text-cyan-300">Final Render "Quantum Bloom"</p>
          <div className="w-full aspect-square rounded-lg overflow-hidden border-2 border-fuchsia-500/50 shadow-2xl shadow-fuchsia-500/30">
            <img src="https://picsum.photos/seed/qaru/800/800" alt="Final render generated by QARU" className="w-full h-full object-cover"/>
          </div>
          <p className="text-xs text-gray-500 mt-2">A work of art, as requested.</p>
        </div>
      </div>
       <style>{`
        @keyframes fade-in {
          from { opacity: 0; transform: scale(0.95); }
          to { opacity: 1; transform: scale(1); }
        }
        .animate-fade-in {
          animation: fade-in 0.5s ease-out forwards;
        }
      `}</style>
    </div>
  );
};

export default Conclusion;
